services:
  - type: web
    name: careai-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: TWILIO_SID
        sync: false
      - key: TWILIO_TOKEN
        sync: false
      - key: TWILIO_PHONE
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: CORS_ORIGIN
        value: https://care-ai-ssibm.web.app,https://care-ai-ssibm.firebaseapp.com
